In [9]:
import pandas as pd

In [10]:
df = pd.read_csv("/content/IMDB Dataset.csv")

In [11]:
df.shape

(50791, 2)

In [13]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [14]:
df["sentiment"].unique()

array(['positive', 'negative'], dtype=object)

In [15]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [16]:
df.drop_duplicates(inplace = True)

In [17]:
df.shape

(49583, 2)

In [18]:
#pre processing
## convert to lower case
df["review"] = df['review'].str.lower()

In [19]:
import re
import pandas as pd

# 2. Define the functions
def remove_html_regex(text):
    return re.sub(r'<.*?>', '', text)

def remove_urls(text):
    return re.sub(r"http\S+", "", text)

def remove_punctuations(text):
    # Notice the ^ to fix the previous bug!
    return re.sub(r"[^A-Za-z0-9\s]", "", text)

# 3. Apply them in the exact correct order
df["review"] = df["review"].apply(remove_html_regex)
df["review"] = df["review"].apply(remove_urls)
df["review"] = df["review"].apply(remove_punctuations)

In [20]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production the filming tech...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

In [21]:
#Removing the stopwords
import nltk # natural language tool kit
nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [22]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [23]:
sample_text = "I like coding in python!"
tokens = word_tokenize(sample_text)
tokens

['I', 'like', 'coding', 'in', 'python', '!']

In [24]:
def remove_stopwords(text):
  tokens = word_tokenize(text)
  stop_words = stopwords.words("english")
  for word in tokens:
    if word in stop_words:
       text.replace(word,"")
  return text

In [25]:
df["review"] = df["review"].apply(remove_stopwords)

In [26]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production the filming tech...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

In [27]:
#Stemming
#porter stemming
from nltk.stem import PorterStemmer
def stemming(text):
  ps = PorterStemmer()
  stemmed_words = []

  tokens = word_tokenize(text)
  for token in tokens:
    stemmed_token = ps.stem(token)
    stemmed_words.append(stemmed_token)
  return " ".join(stemmed_words)

In [28]:
df["review"] = df["review"].apply(stemming)

In [29]:
df.head()

                                              review sentiment
0  one of the other review ha mention that after ...  positive
1  a wonder littl product the film techniqu is ve...  positive
2  i thought thi wa a wonder way to spend time on...  positive
3  basic there a famili where a littl boy jake th...  negative
4  petter mattei love in the time of money is a v...  positive

In [30]:
# Encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["sentiment"]= le.fit_transform(df["sentiment"])

In [31]:
y = df["sentiment"]

In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer(max_features=5000)
x = tf.fit_transform(df["review"])

In [33]:
x

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 5804518 stored elements and shape (49583, 5000)>

In [34]:
print(x)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 5804518 stored elements and shape (49583, 5000)>
  Coords	Values
  (0, 3137)	0.020662812963652775
  (0, 3114)	0.0966086840263282
  (0, 4452)	0.19844939127176198
  (0, 3165)	0.05801188317274902
  (0, 3705)	0.0485809826021295
  (0, 2037)	0.025146827927055863
  (0, 2824)	0.051569275837737946
  (0, 4451)	0.06356975811588811
  (0, 166)	0.03291191258941437
  (0, 4829)	0.07971414678887735
  (0, 2490)	0.04921150135360222
  (0, 3197)	0.4374957561507432
  (0, 1546)	0.10401835004017197
  (0, 4987)	0.053644579732150116
  (0, 448)	0.0578425122270219
  (0, 2189)	0.07249661580873348
  (0, 4465)	0.024781062729099204
  (0, 302)	0.041810891615442755
  (0, 3728)	0.08360202974653706
  (0, 329)	0.07628003195029039
  (0, 4470)	0.043537592393911376
  (0, 2399)	0.13118621170564634
  (0, 1592)	0.05665705451897378
  (0, 4870)	0.051050277615138806
  (0, 2065)	0.04169056308442633
  :	:
  (49582, 2297)	0.09366615151841848
  (49582, 1664)	0.16528428333301204
  (49582, 2218)	0.08219675803378373
  (49582, 4609)	0.09126510003468608
  (49582, 781)	0.1059913577539743
  (49582, 3843)	0.09716070275826902
  (49582, 2538)	0.10979056464970512
  (49582, 4666)	0.10112308301783432
  (49582, 2601)	0.0925019829129092
  (49582, 2366)	0.13966239886170814
  (49582, 385)	0.11230136482776219
  (49582, 2073)	0.12361225763771727
  (49582, 3655)	0.105195335174328
  (49582, 2279)	0.16039930283653472
  (49582, 321)	0.10464331150467322
  (49582, 4589)	0.15479729199221362
  (49582, 2526)	0.17831104759174796
  (49582, 4172)	0.19507502205047064
  (49582, 1094)	0.15513465530800538
  (49582, 687)	0.14311827963088508
  (49582, 3041)	0.15998482479846343
  (49582, 2957)	0.16858832358559317
  (49582, 783)	0.12531122045043727
  (49582, 1969)	0.15309614363294616
  (49582, 3656)	0.14699634790037022

In [35]:
x.shape

(49583, 5000)

In [36]:

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=42,test_size=0.2)

In [37]:
x_train = x_train.toarray()
x_test = x_test.toarray()

In [38]:
print(type(y_train))
print(type(x_train))

<class 'pandas.core.series.Series'>
<class 'numpy.ndarray'>

In [39]:
## DataLoaders
from torch.utils.data import DataLoader , TensorDataset

In [40]:
import torch
train_set = TensorDataset(torch.from_numpy(x_train).float(),torch.from_numpy(y_train.values).float())
test_set = TensorDataset(torch.from_numpy(x_test).float(),torch.from_numpy(y_test.values).float())

In [41]:
train_loader = DataLoader(train_set,shuffle = True,batch_size=64)
test_loader = DataLoader(test_set,batch_size=64)

In [42]:
# Building RNN
import torch.nn as nn
import torch.optim as optim

In [46]:
class RNN(nn.Module):
  def __init__(self,input_size,hidden_size=128,num_layers=1):
    super().__init__()

    self.hidden_size = hidden_size
    self.num_layers = num_layers

    #RNN Layer
    self.rnn = nn.RNN(input_size,hidden_size,num_layers,batch_first = True)

    #fc layer
    self.fc = nn.Linear(hidden_size,1)

  def forward(self,x):
    h0 = torch.zeros(self.num_layers,x.size(0),self.hidden_size)
    out,_ = self.rnn(x,h0)
    out = self.fc(out[:,-1,:])
    return out

In [47]:
input_size = x_train.shape[1]
model = RNN(input_size)
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters())

In [48]:
epochs = 10

for epoch in range(epochs):
    model.train()

    for Xb, yb in train_loader:
        optimizer.zero_grad()

        Xb = Xb.unsqueeze(1) # add singleton direction

        outputs = model(Xb) # (batch_size, 1)

        outputs = torch.sigmoid(outputs.squeeze()) # (batch_size,) => probability

        loss = criterion(outputs, yb) # compute loss
        loss.backward() # backprop
        optimizer.step() # weights update

    print(f"epoch = {epoch+1}/{epochs} and loss = {loss.item()}")

epoch = 1/10 and loss = 0.27341341972351074
epoch = 2/10 and loss = 0.27222901582717896
epoch = 3/10 and loss = 0.33552178740501404
epoch = 4/10 and loss = 0.34089288115501404
epoch = 5/10 and loss = 0.2995093762874603
epoch = 6/10 and loss = 0.1975625604391098
epoch = 7/10 and loss = 0.2609190046787262
epoch = 8/10 and loss = 0.12640434503555298
epoch = 9/10 and loss = 0.2719566822052002
epoch = 10/10 and loss = 0.18848539888858795

In [49]:
model.eval()

with torch.no_grad():
    correct_vals = 0
    tot_vals = 0

    for Xb, yb in test_loader:
        Xb = Xb.unsqueeze(1)

        outputs = model(Xb)
        predicted = (torch.sigmoid(outputs.squeeze()) > 0.5).float()

        tot_vals += yb.size(0)
        correct_vals += (predicted == yb).sum().item()

    print(f"accuracy = {correct_vals/tot_vals*100}")

accuracy = 87.17354038519713